services:
  web:
    build: .
    ports:
      - "8008:8008"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - OPENWEATHER_API_KEY=${OPENWEATHER_API_KEY}
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key}
      - DATABASE_URL=sqlite:////app/instance/weather.db
    volumes:
      # Mount only necessary directories
      - .:/app
    # Remove user specification for Windows compatibility
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8008/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  weather-data:
